# Generated by Django 5.0 on 2023-12-18 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestformapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestform',
            name='contact',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator(message='Contact must be 10 digits', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
    ]
